# Configuration for pre-commit: A framework for managing and maintaining multi-language pre-commit hooks.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
  - id: end-of-file-fixer
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.6.0
  hooks:
  - id: shellcheck
- repo: https://github.com/adrienverge/yamllint.git
  rev: master
  hooks:
  - id: yamllint
